### ISSUE TITLE
Clarification on which version of OpenCV

### ISSUE THREAD

**Issue by joshuajnoble** [AlexeyAB/darknet#1280]
I've been reading through this thread https://github.com/opencv/opencv/issues/10963 and seeing lots of discussion https://github.com/AlexeyAB/darknet/issues/500 and https://github.com/AlexeyAB/darknet/issues/414 but I can't compile with OpenCV 3.4.0, I get the errors:

`1>------ Build started: Project: darknet, Configuration: Debug x64 ------
1>http_stream.cpp
1>c:\users\winbase\code\opencv\build\include\opencv2\flann\matrix.h(70): warning C4003: not enough actual parameters for macro 'free'
1>c:\users\winbase\code\opencv\build\include\opencv2\flann\matrix.h(70): error C2059: syntax error: ','
1>c:\users\winbase\code\opencv\build\include\opencv2\flann\matrix.h(87): note: see reference to class template instantiation 'cvflann::Matrix<T>' being compiled
1>c:\users\winbase\code\opencv\build\include\opencv2\core\cuda.hpp(106): error C2059: syntax error: 'constant'`

from matrix.h

` /**
     * Convenience function for deallocating the storage data.
     */
    CV_DEPRECATED void free()
    {
        fprintf(stderr, "The cvflann::Matrix<T>::free() method is deprecated "
                "and it does not do any memory deallocation any more.  You are"
                "responsible for deallocating the matrix memory (by doing"
                "'delete[] matrix.data' for example)");
    }
`

Is there any guidance on which version of OpenCV 3 is compatible with Darknet? I can compile with 2.4.13 but in running `darknet detector train` it always crashes on `try to allocate workspace`. Without OpenCV I can train without problems. I'm not sure how to get the OpenCV compatibility. I'm using Windows 10, Visual Studio 2017, CUDA 9.2, and the following flags:

`OPENCV;CUDNN;_CRTDBG_MAP_ALLOC;_MBCS;_TIMESPEC_DEFINED;_CRT_SECURE_NO_WARNINGS;_CRT_RAND_S;GPU;WIN32;NDEBUG;_CONSOLE;_LIB;%(PreprocessorDefinitions)`

**Comment by joshuajnoble** [comment]
OpenCV 3.3.0 errors out with:

`1>c:\users\winbase\code\opencv\build\include\opencv2\core\cvdef.h(58): error C2061: syntax error: identifier 'cv' (compiling source file ..\..\src\voxel.c)`

The C++ is still getting brought into the compile somehow, not sure how other folks are getting around this.

**Comment by AshleyRoth** [comment]
@AlexeyAB Hello! Can you explain me please. For what it answers here // get_region_boxes (l, 1, 1, thresh, probs, boxes, 0, 0); and why is now commented on? Not used or replaced?

**Comment by vinjn** [comment]
I am using OpenCV 3.4.0 for months :)
