### ISSUE TITLE
Compile on ubuntu 16.04 with opencv 3.x

### ISSUE THREAD

**Issue by cvDreamer** [AlexeyAB/darknet#375]
I got this error when running 'make':

In file included from /usr/local/include/opencv2/core/core_c.h:48:0,
                 from /usr/local/include/opencv2/highgui/highgui_c.h:45,
                 from ./src/image.c:14:
/usr/local/include/opencv2/highgui/highgui_c.h:139:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘:’ token
 CVAPI(cv::Rect)cvGetWindowImageRect(const char* name);
 ^
compilation terminated due to -Wfatal-errors.
Makefile:89: recipe for target 'obj/image.o' failed
make: *** [obj/image.o] Error 1

Please help!

**Comment by AlexeyAB** [comment]
What OpenCV version do you use?

**Comment by cvDreamer** [comment]
OpenCV 3.4.0

The Makefile is like below:

GPU=1
CUDNN=0
OPENCV=1
DEBUG=0
OPENMP=1
LIBSO=1

**Comment by cvDreamer** [comment]
Any insight @AlexeyAB ?

**Comment by AlexeyAB** [comment]
* Try to build LIBSO=0 OPENMP=0
* What compiler version do you use?

* Try to build this simple OpenCV app, can you build it?
```c
#include "cv.h"
#include "highgui.h"
int main(){

}
	

opencv-test:
    gcc -o opencv-test opencv-test.c `pkg-config opencv --cflags --libs`
```

* What command line did you use for build OpenCV?
* Try to use OpenCV 3.3.0
* As I see it is a common error for yolo + OpenCV: https://www.google.ru/search?q=highgui_c.h:139:1:+error:+expected+%E2%80%98%3D%E2%80%99,+%E2%80%98,%E2%80%99,+%E2%80%98%3B%E2%80%99,+%E2%80%98asm%E2%80%99+or+%E2%80%98attribute%E2%80%99+before+%E2%80%98:%E2%80%99+token&newwindow=1&rlz=1C1MSIM_enRU714RU714&filter=0&biw=1536&bih=735
