### ISSUE TITLE
undefined reference to IplImage

### ISSUE THREAD

**Issue by alexanderfrey** [AlexeyAB/darknet#2941]
Hi,

when I run make it throws me `yolo_console_dll.cpp:(.text+0x4b11): undefined reference to _IplImage::_IplImage(cv::Mat const&)`

No matter if I compile with OpenCV 3.4.3 or OpenCV 4.0.1

Any ideas whtas wrong ?

Best
Alexander

**Comment by alexanderfrey** [comment]
Btw. I'm on commit 8c970498a296ed129ffef7d872ccc25d42d1afda

**Comment by AlexeyAB** [comment]
I will try to fix it.

**Comment by AlexeyAB** [comment]
@alexanderfrey I fixed this issue.

**Comment by alexanderfrey** [comment]
Thanks ! Wasn't sure if it is something with my setup or your code.

Let me know if I can help !

**Comment by alexanderfrey** [comment]
Thanks a lot !
