### ISSUE TITLE
Functions no longer supported with latest cuDNN

### ISSUE THREAD

**Issue by ptkahl** [AlexeyAB/darknet#5905]
FILE: src/convolution_layer.c
LINES: 304, 312, and 320 (in version prior to 10 July 2020)
ISSUE: With Nvidia's recent release of CUDA 11.0, a corresponding cudNN 8.0 was released that does not include functions cudnnGetConvolutionForwardAlgorithm(), cudnnGetConvolutionBackwardDataAlgorithm(), and cudnnGetConvolutionBackwardFilterAlgorithm(), nor their respectively associated typdefs: cudnnConvolutionFwdPreference_t, cudnnConvolutionBwdDataPreference_t, and cudnnConvolutionBwdFilterPreference_t. (See Table 3 in https://docs.nvidia.com/deeplearning/sdk/cudnn-api/#api-changes.)

There may be similar cuDNN functions that can serve the intended purposes of these discontinued functions. For example, function cudnnGetConvolutionForwardAlgorithm_v7() is very similar to cudnnGetConvolutionForwardAlgorithm() in its description, but the parameters are not all the same.

Notes:
1. AlexeyAB posted a fix on 10 July 2020 (https://github.com/AlexeyAB/darknet/commit/cb9148b38f8d2c5cec9ba717916268745235850c) but commented "cuDNN 8.0 supported (but works slow)" so it is not clear if this issue should be closed. The slowness may be due to cuDNN 8 performance rather than AlexeyAB's fix. The earlier cuDNN 8 versions were labeled as "Preview" versions and performance optimization was a noted issue. The Release Notes for cuDNN 8.0.3 indicate that most performance issues have been resolved. I recommend re-testing with the lastest versions of CUDA 11 and cuDNN 8 to see if AlexeyAB's fix still suffers from slow performance compared to previous code using CUDA 12 with cuDNN 7.

2. AlexyAB posted another fix on 5 September 2020 (https://github.com/AlexeyAB/darknet/commit/eb0272f27acda1982fe4d30acd838fca427785a9) that is hoped to better address performance issues when using cuDNN 8. With this latest change, this issue should be closed.

Additional Notes:
- To allow for compiling with gcc v9.x and to take advantage of the latest Nvidia GPU features, making the code work with CUDA 11.0 and cudNN 8.0 is highly recommended.
- There is a similar issue posted to Stack Overflow (see https://stackoverflow.com/questions/62266086/converting-from-deprecated-cudnn-functions-to-working-ones).

**Comment by Avnsx** [comment]
Hey same issue here, I would strongly appreciate it if this case would be looked after and updated accordignly to newest cuda standards!

**Comment by vfbsilva** [comment]
I have the same issue with the following setup:
community/cuda 11.1.0-2 [instalado]
    NVIDIA's GPU programming toolkit
community/cudnn 8.0.4.30-1 [instalado]
gcc (GCC) 10.2.0

on manjaro linux.

When compilling it fails it with:
```
gcc -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4` -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/convolutional_layer.c -o obj/convolutional_layer.o
./src/convolutional_layer.c: In function ‘cudnn_convolutional_setup’:
./src/convolutional_layer.c:284:24: error: ‘CUDNN_CONVOLUTION_FWD_PREFER_FASTEST’ undeclared (first use in this function); did you mean ‘CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3’?
  284 |     int forward_algo = CUDNN_CONVOLUTION_FWD_PREFER_FASTEST;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```


I'm not familiar with the insides of the project so I wonder is there a work around this issue?

**Comment by vfbsilva** [comment]
Bump, any news regarding this issue or a work around?

**Comment by ptkahl** [comment]
I believe this issue was successfully addressed about half-a-year ago. I
have only tested the "fix" on my system, but it seems to work. I updated
the issue text some time ago, suggesting that it should be closed.

Sincerely,
Patrick Kahl

**Comment by AlexeyAB** [comment]
Issue partially resolved on July 10, 2020, fully resolved on November 10, 2020 (when cuDNN 8.0.5 was released).

It works well with this configurations without any issue:
* Windows7 x64 + CUDA 11.1 + cuDNN 8.0.5 + GeForce RTX 3090
* Linux x64 +  CUDA 11.1 + cuDNN 8.0.5 + Quadro RTX 6000
* Windows10 x64 + CUDA 11.1 + cuDNN 8.0.5 + GTX 1080 Ti


![image](https://user-images.githubusercontent.com/4096485/103704315-28aefc80-4fba-11eb-9a6c-8828b6b79b65.png)
![image](https://user-images.githubusercontent.com/4096485/103704351-349abe80-4fba-11eb-9233-178324a31225.png)
