### PR TITLE
Turn the C_STANDARD knob up to 11

### LINKED ISSUE #4825: Project should explicitly set C standard, or fail to build on some compilers
On Linux with gcc 4.8.5, recent checkouts of this repo will fail to build:

```
darknet/src/classifier.c: In function ‘try_classifier’:
darknet/src/classifier.c:756:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for(int i = 0; i < l.c; ++i){
         ^
```

Adding `-DCMAKE_C_STANDARD=99` to the CMake options works.

This seems to have broken with 3c4ddd65c5ee4fafabc1f0d75a50de1ab5841ca9.

The C standard should be set to C99 in the CMakeLists.txt file

### PR DESCRIPTION
**Pull request by imaami**
This makes CMake request the 2011 C standard feature set from the C compiler. CMake will automatically fall back to an earlier standard if C11 isn't supported, so older compilers should continue to work after this change.

Fixes #4825

### CODE REVIEW

**Comment by cenit** [comment]
shouldn't be necessary anymore, it was better to fix the code than moving the required C standard up
