### ISSUE TITLE
Cannot build with make on CUDA 11.0.

### ISSUE THREAD

**Issue by pasutisu** [AlexeyAB/darknet#6361]
I tried to build Darknet on following environment.

* OS: Arch Linux
* CUDA: 11.0 (on official repository)
* Compile with: make
* Compile option: GPU=1

But I got error on NVCC tried to build cu files.

```
$ make -j7
~~~~~
nvcc fatal   : Unsupported gpu architecture 'compute_30'
```

It looks like Kepler(generic) support discontinued after CUDA 11.0.
https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#virtual-architecture-feature-list

**Comment by jpoberhauser** [comment]
Hi @pasutisu 

I tried the fix you showcase here and the `make` step works. 

Now I'm having an issue actually running darknet though, the error I am now facing is:


```
CUDA status Error: file: ./src/convolutional_kernels.cu : () : line: 138 : build time: Sep  2 2020 - 10:45:05 

 CUDA Error: no kernel image is available for execution on the device
CUDA Error: no kernel image is available for execution on the device: Success
darknet: ./src/utils.c:325: error: Assertion `0' failed.
Aborted (core dumped)
```
I'm wondering if you faced the same issue? 

Im using CUDA 11.0 and Driver Version: 450.51.06 on Ubuntu 18.04

**Comment by pasutisu** [comment]
@jpoberhauser 
What card do you use?
My patch only fixes that problem came from CUDA 11.0 dropped Kepler(compute_30) support.
If you use optional supported card that commented in makefile, you need to uncomment your card,

**Comment by bizmate** [comment]
I am also seeing this error, i removed line
https://github.com/AlexeyAB/darknet/blob/master/Makefile#L20
and added ARCH= in the next line in make file and so removed it from the compatible architectures. 

Now running and getting error 

```
./darknet  detector demo build/darknet/x64/data/coco.data ~/Documents/siti-web/yolo-lib/yolov3.cfg ~/Documents/siti-web/yolo-lib/yolov3.weights  /media/2TBStore/Media/Video/cctv/tp/2019/11/05/Reolink401_TP_1_01_20191105081614.mp4 -dont_show -ext_output
CUDA status Error: file: /home/bizmate/Documents/siti-web/darknet-ab/src/dark_cuda.c : () : line: 39 : build time: Oct 15 2020 - 08:11:33 

 CUDA Error: initialization error
CUDA Error: initialization error: No such file or directory
```
