### ISSUE TITLE
Project should explicitly set C standard, or fail to build on some compilers

### ISSUE THREAD

**Issue by rgov** [AlexeyAB/darknet#4825]
On Linux with gcc 4.8.5, recent checkouts of this repo will fail to build:

```
darknet/src/classifier.c: In function ‘try_classifier’:
darknet/src/classifier.c:756:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for(int i = 0; i < l.c; ++i){
         ^
```

Adding `-DCMAKE_C_STANDARD=99` to the CMake options works.

This seems to have broken with 3c4ddd65c5ee4fafabc1f0d75a50de1ab5841ca9.

The C standard should be set to C99 in the CMakeLists.txt file

**Comment by AlexeyAB** [comment]
You can try to ask it there: https://github.com/AlexeyAB/darknet/pull/3815
