### ISSUE TITLE
Unable to build Darknet Ubuntu 16.04, OpenCV 3.3.1, CMake 3.8

### ISSUE THREAD

**Issue by Christopheraburns** [AlexeyAB/darknet#2829]
Can anyone see where I went wrong from this error?

[97%] Built target darknet
[ 98%] Linking CXX executable uselib_track
[ 98%] Linking CXX executable uselib
/usr/bin/ld: CMakeFiles/uselib.dir/src/yolo_console_dll.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/uselib.dir/build.make:124: recipe for target 'uselib' failed
make[2]: *** [uselib] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/uselib.dir/all' failed
make[1]: *** [CMakeFiles/uselib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: CMakeFiles/uselib_track.dir/src/yolo_console_dll.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/uselib_track.dir/build.make:124: recipe for target 'uselib_track' failed
make[2]: *** [uselib_track] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/uselib_track.dir/all' failed
make[1]: *** [CMakeFiles/uselib_track.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
-- Found cuDNN: v7.4.1  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
CMake Warning at CMakeLists.txt:201 (message):
  To build with OpenMP support you need CMake 3.9.0+

**Comment by cenit** [comment]
Which compiler and which version of it are you using? There’s a fix for clang on the head of the master exactly for this problem. Update the repo and it should be fine, if it’s your case
