### ISSUE TITLE
OpenCV IplImage Errors

### ISSUE THREAD

**Issue by acidtonic** [AlexeyAB/darknet#1826]
I am trying to build on Gentoo with OpenCV 3.4 and getting these errors.

I am able to build the original darknet and my own opencv code using C++ but for some reason this fork refuses to build. I uninstalled gentoo provided OpenCV and built from source due to requiring object tracker from contrib (and gentoo packages not properly building tracker). I hope this isn't an incompatibility with the latest OpenCV.

Any ideas?

```
gcc  -DOPENCV `pkg-config --cflags opencv` -DGPU -I/opt/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -ffp-contract=fast -mavx -mavx2 -msse3 -msse4.1 -msse4.2 -msse4a -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/opt/cudnn/include -fPIC -c ./src/image.c -o obj/image.o
In file included from /usr/include/opencv2/core/core_c.h:48:0,
                 from /usr/include/opencv2/highgui/highgui_c.h:45,
                 from ./src/image.c:14:
/usr/include/opencv2/core/types_c.h: In function 'cvIplImage':
/usr/include/opencv2/core/types_c.h:370:12: error: incompatible types when returning type 'int' but 'IplImage {aka struct _IplImage}' was expected
     return _IplImage();
            ^~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:136: obj/image.o] Error 1
```

**Comment by PeterQuinn925** [comment]
It's an incompatibility with version 3.4 of OpenCV. See https://github.com/pjreddie/darknet/issues/551

**Comment by acidtonic** [comment]
Thanks! I have been assuming this was my fault due to custom building....

What I am curious about however is that the original darknet used the C++ API and this fork seems to have downgraded back to the C API.

Was this decision purely for performance reasons? I guess now my thought is why not backport the C++ OpenCV from the original darknet and fix this? Unless there are good reasons I'm half tempted to do this myself.
