### ISSUE TITLE
Can't compile with opnecv=1

### ISSUE THREAD

**Issue by ahsan856jalal** [AlexeyAB/darknet#932]
Ubuntu 16.04
OpenCV=3.4.0
python 2.7.14

when I make opencv=1 in Makefile and try to compile it , it gave me this error:

In file included from /usr/local/include/opencv2/core/types_c.h:59:0,
                 from /usr/local/include/opencv2/core/core_c.h:48,
                 from /usr/local/include/opencv2/highgui/highgui_c.h:45,
                 from ./src/image.c:14:
/usr/local/include/opencv2/core/cvdef.h:485:1: error: unknown type name ‘namespace’
 namespace cv {
 ^
compilation terminated due to -Wfatal-errors.
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -c ./src/blas.c -o obj/blas.o
Makefile:130: recipe for target 'obj/image.o' failed
make: *** [obj/image.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by ahsan856jalal** [comment]
I have 3.4.1 installed when I checked with pkg-config --modversion opencv 
while it is showing me 3.4.0 when I do import cv2;cv2._version__ in python environment

**Comment by sherlocked777** [comment]
I have the same issue, how to get rid of this error?

**Comment by AlexeyAB** [comment]
@sherlocked777 Install OpenCV 3.4.0.
OpenCV 3.4.1 has a bug in C API.

https://github.com/AlexeyAB/darknet#you-only-look-once-unified-real-time-object-detection-versions-2--3

> This repository supports:
> 
> both Windows and Linux
> both OpenCV 2.x.x and OpenCV <= 3.4.0 **(3.4.1 and higher isn't supported)**
> both cuDNN v5-v7
> CUDA >= 7.5
> also create SO-library on Linux and DLL-library on Windows

**Comment by komalpharate** [comment]
Hi,
I had opencv3.4.1
Uninstalled it completely
Installed 3.3.0
Still getting this namespace bug.
The fix to solve the bug for 3.4.1 is to change modules/core/include/opencv/core/cvdef.h
But this cant work with 3.3.0 as it doesnt have the same cvdef.h file
I have the older darknet yolov2 git version. 
I tried make on current darknet, it works fine.
Can I know how to solve it for older darknet ?
