### ISSUE TITLE
Cmake errors - c++ application

### ISSUE THREAD

**Issue by erlendhade** [AlexeyAB/darknet#1597]
Hi

I am realizing that my expertise is just not cutting it to get darknet.so working in my application.
When I try to build my application, i just get a mountain of errors:

````
/snap/clion/38/bin/cmake/linux/bin/cmake --build /home/bachelor/CLionProjects/Utkikk9000/cmake-build-debug --target Utkikk9000 -- -j 1
[ 50%] Linking CXX executable Utkikk9000
/home/bachelor/darknet-master/darknet: In function `main':
(.text+0x3d0): multiple definition of `main'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/home/bachelor/CLionProjects/Utkikk9000/main.cpp:9: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0xd8): multiple definition of `guard variable for cvflann::anyimpl::SinglePolicy<cvflann::flann_algorithm_t>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0x148): multiple definition of `cvflann::anyimpl::SinglePolicy<cvflann::anyimpl::empty_any>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0x108): multiple definition of `cvflann::anyimpl::SinglePolicy<cv::String>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet: In function `_start':
(.text+0x1650): multiple definition of `_start'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o:(.text+0x0): first defined here
/home/bachelor/darknet-master/darknet: In function `_fini':
(.fini+0x0): multiple definition of `_fini'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o:(.fini+0x0): first defined here
/home/bachelor/darknet-master/darknet:(.bss+0x120): multiple definition of `cvflann::anyimpl::SinglePolicy<cvflann::flann_algorithm_t>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet: In function `__data_start':
(.data+0x0): multiple definition of `__data_start'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o:(.data+0x0): first defined here
/home/bachelor/darknet-master/darknet:(.bss+0xe0): multiple definition of `guard variable for cvflann::anyimpl::SinglePolicy<bool>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0xc0): multiple definition of `guard variable for cvflann::anyimpl::SinglePolicy<cv::String>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0x140): multiple definition of `cvflann::anyimpl::SinglePolicy<char const*>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0xd0): multiple definition of `guard variable for cvflann::anyimpl::SinglePolicy<cvflann::flann_centers_init_t>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0x100): multiple definition of `guard variable for cvflann::anyimpl::SinglePolicy<cvflann::anyimpl::empty_any>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0x118): multiple definition of `cvflann::anyimpl::SinglePolicy<cvflann::flann_centers_init_t>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0xc8): multiple definition of `guard variable for cvflann::anyimpl::SinglePolicy<unsigned int>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0x110): multiple definition of `cvflann::anyimpl::SinglePolicy<unsigned int>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0xf0): multiple definition of `guard variable for cvflann::anyimpl::SinglePolicy<int>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet: In function `_init':
(.init+0x0): multiple definition of `_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o:(.init+0x0): first defined here
/home/bachelor/darknet-master/darknet:(.bss+0x128): multiple definition of `cvflann::anyimpl::SinglePolicy<bool>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0xf8): multiple definition of `guard variable for cvflann::anyimpl::SinglePolicy<char const*>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet: In function `__data_start':
(.data+0x8): multiple definition of `__dso_handle'
/usr/lib/gcc/x86_64-linux-gnu/5/crtbegin.o:(.data+0x0): first defined here
/home/bachelor/darknet-master/darknet:(.bss+0xe8): multiple definition of `guard variable for cvflann::anyimpl::SinglePolicy<float>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.rodata+0x0): multiple definition of `_IO_stdin_used'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o:(.rodata.cst4+0x0): first defined here
/home/bachelor/darknet-master/darknet:(.bss+0x138): multiple definition of `cvflann::anyimpl::SinglePolicy<int>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/home/bachelor/darknet-master/darknet:(.bss+0x130): multiple definition of `cvflann::anyimpl::SinglePolicy<float>::policy'
CMakeFiles/Utkikk9000.dir/main.cpp.o:/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:248: first defined here
/usr/lib/gcc/x86_64-linux-gnu/5/crtend.o:(.tm_clone_table+0x0): multiple definition of `__TMC_END__'
/home/bachelor/darknet-master/darknet:(.nvFatBinSegment+0x0): first defined here
/usr/bin/ld: error in /home/bachelor/darknet-master/darknet(.eh_frame); no .eh_frame_hdr table will be created.
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `detect_mat':
/home/bachelor/darknet-master/src/yolo_v2_class.cpp:45: undefined reference to `cv::imdecode(cv::_InputArray const&, int)'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `get_device_count':
/home/bachelor/darknet-master/src/yolo_v2_class.cpp:66: undefined reference to `cudaGetDeviceCount'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `get_device_name':
/home/bachelor/darknet-master/src/yolo_v2_class.cpp:76: undefined reference to `cudaGetDeviceProperties'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `check_cuda(cudaError)':
/home/bachelor/darknet-master/src/yolo_v2_class.cpp:88: undefined reference to `cudaGetErrorString'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `Detector::Detector(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)':
/home/bachelor/darknet-master/src/yolo_v2_class.cpp:108: undefined reference to `cudaGetDevice'
/home/bachelor/darknet-master/src/yolo_v2_class.cpp:145: undefined reference to `cudaSetDevice'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `Detector::~Detector()':
/home/bachelor/darknet-master/src/yolo_v2_class.cpp:163: undefined reference to `cudaGetDevice'
/home/bachelor/darknet-master/src/yolo_v2_class.cpp:170: undefined reference to `cudaSetDevice'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `Detector::detect(image_t, float, bool)':
/home/bachelor/darknet-master/src/yolo_v2_class.cpp:245: undefined reference to `cudaGetDevice'
/home/bachelor/darknet-master/src/yolo_v2_class.cpp:247: undefined reference to `cudaSetDevice'
/home/bachelor/darknet-master/src/yolo_v2_class.cpp:319: undefined reference to `cudaSetDevice'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `draw_boxes(cv::Mat, std::vector<bbox_t, std::allocator<bbox_t> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, int, int)':
/home/bachelor/darknet-master/src/yolo_console_dll.cpp:188: undefined reference to `cv::rectangle(cv::Mat&, cv::Rect_<int>, cv::Scalar_<double> const&, int, int, int)'
/home/bachelor/darknet-master/src/yolo_console_dll.cpp:192: undefined reference to `cv::getTextSize(cv::String const&, int, double, int, int*)'
/home/bachelor/darknet-master/src/yolo_console_dll.cpp:196: undefined reference to `cv::rectangle(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
/home/bachelor/darknet-master/src/yolo_console_dll.cpp:197: undefined reference to `cv::putText(cv::_InputOutputArray const&, cv::String const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
/home/bachelor/darknet-master/src/yolo_console_dll.cpp:202: undefined reference to `cv::putText(cv::_InputOutputArray const&, cv::String const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `main':
/home/bachelor/CLionProjects/Utkikk9000/main.cpp:19: undefined reference to `cv::VideoCapture::VideoCapture(int)'
/home/bachelor/CLionProjects/Utkikk9000/main.cpp:21: undefined reference to `cv::VideoCapture::isOpened() const'
/home/bachelor/CLionProjects/Utkikk9000/main.cpp:23: undefined reference to `cv::VideoCapture::operator>>(cv::Mat&)'
/home/bachelor/CLionProjects/Utkikk9000/main.cpp:30: undefined reference to `cv::namedWindow(cv::String const&, int)'
/home/bachelor/CLionProjects/Utkikk9000/main.cpp:31: undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
/home/bachelor/CLionProjects/Utkikk9000/main.cpp:33: undefined reference to `cv::waitKey(int)'
/home/bachelor/CLionProjects/Utkikk9000/main.cpp:19: undefined reference to `cv::VideoCapture::~VideoCapture()'
/home/bachelor/CLionProjects/Utkikk9000/main.cpp:19: undefined reference to `cv::VideoCapture::~VideoCapture()'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `cv::String::String(char const*)':
/usr/local/include/opencv2/core/cvstd.hpp:602: undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `cv::String::~String()':
/usr/local/include/opencv2/core/cvstd.hpp:648: undefined reference to `cv::String::deallocate()'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `cv::String::operator=(cv::String const&)':
/usr/local/include/opencv2/core/cvstd.hpp:656: undefined reference to `cv::String::deallocate()'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `cv::Mat::Mat(cv::Mat const&)':
/usr/local/include/opencv2/core/mat.inl.hpp:490: undefined reference to `cv::Mat::copySize(cv::Mat const&)'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
/usr/local/include/opencv2/core/mat.inl.hpp:500: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
/usr/local/include/opencv2/core/mat.inl.hpp:515: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `cv::Mat::~Mat()':
/usr/local/include/opencv2/core/mat.inl.hpp:692: undefined reference to `cv::fastFree(void*)'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `cv::Mat::operator=(cv::Mat const&)':
/usr/local/include/opencv2/core/mat.inl.hpp:713: undefined reference to `cv::Mat::copySize(cv::Mat const&)'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `cv::Mat::release()':
/usr/local/include/opencv2/core/mat.inl.hpp:804: undefined reference to `cv::Mat::deallocate()'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `cv::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/local/include/opencv2/core/cvstd.inl.hpp:83: undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `Detector::mat_to_image_resize(cv::Mat) const':
/home/bachelor/darknet-master/src/yolo_v2_class.hpp:105: undefined reference to `cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `Detector::mat_to_image(cv::Mat)':
/home/bachelor/darknet-master/src/yolo_v2_class.hpp:115: undefined reference to `cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `cv::Mat::Mat<char>(std::vector<char, std::allocator<char> > const&, bool)':
/usr/local/include/opencv2/core/mat.inl.hpp:574: undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
CMakeFiles/Utkikk9000.dir/main.cpp.o: In function `void __gnu_cxx::new_allocator<_IplImage>::construct<_IplImage, cv::Mat&>(_IplImage*, cv::Mat&)':
/usr/include/c++/5/ext/new_allocator.h:120: undefined reference to `_IplImage::_IplImage(cv::Mat const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/Utkikk9000.dir/build.make:84: recipe for target 'Utkikk9000' failed
make[3]: *** [Utkikk9000] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/Utkikk9000.dir/all' failed
make[2]: *** [CMakeFiles/Utkikk9000.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/Utkikk9000.dir/rule' failed
make[1]: *** [CMakeFiles/Utkikk9000.dir/rule] Error 2
Makefile:118: recipe for target 'Utkikk9000' failed
make: *** [Utkikk9000] Error 2
````

If anyone can point me in the right direction on how to fix this, it would be greatly appreciated.

**Comment by PeterQuinn925** [comment]
Dumb question - If you comment out the calls to darknet, does your application compile? Have you posted your source someplace? Without it, it's going to be really hard to help.

**Comment by erlendhade** [comment]
Hi Peter

main.cpp

```
#include <iostream>
#define OPENCV
#include <yolo_v2_class.cpp>
#include <yolo_console_dll.cpp>
#include <yolo_v2_class.hpp>



int main() {
    std::string cfg = "/home/bachelor/darknet-master/cfg/yolov3-Utkikk9000.cfg";
    std::string weights = "/home/bachelor/darknet-master/yolov3-Utkikk9000_v2.0_best.weights";
    std::string names = "/home/bachelor/darknet-master/data/obj.names";
    int gpu = 0;                                                                                             //GPU index
    float det_thresh = 0.5;                                                                                  //Detection threshold

    Detector detector(cfg, weights, gpu);
    auto obj_names = objects_names_from_file(names);

    cv::VideoCapture cap(0);

    while (cap.isOpened()){
        cv::Mat frame;
        cap >> frame;
        std::vector<bbox_t> result_vec;
        result_vec = detector.detect(frame, det_thresh);

        draw_boxes(frame, result_vec, obj_names);
        show_console_result(result_vec, obj_names);

        cv::namedWindow("Test");
        cv::imshow("Test", frame);

        if(cv::waitKey(10) == 27){
            break;
        }
    }

    return 0;
}
```

CmakeList.txt

```
cmake_minimum_required(VERSION 3.12)
project(Utkikk9000)

set(CMAKE_CXX_STANDARD 14)

add_executable(Utkikk9000 main.cpp)

add_compile_definitions(GPU)

include_directories(BEFORE /home/bachelor/darknet-master/src /usr/local/cuda-9.1/include)

link_directories(/home/bachelor/darknet-master)

target_link_libraries(Utkikk9000 /home/bachelor/darknet-master/darknet)
```

CUDA 9.1 is installed
Working on Ubuntu 16.04

Really appreciate you taking the time to help a less enlightened!

**Comment by AlexeyAB** [comment]
Remove these lines:
```cpp
#include <yolo_v2_class.cpp>
#include <yolo_console_dll.cpp>
```

If it doesn't help, try to remove this line: `add_compile_definitions(GPU)`

**Comment by erlendhade** [comment]
Did what you suggestes Alexey

still get a few errors though..

```
/snap/clion/38/bin/cmake/linux/bin/cmake --build /home/bachelor/CLionProjects/Utkikk9000/cmake-build-debug --target Utkikk9000 -- -j 1
Scanning dependencies of target Utkikk9000
[ 50%] Building CXX object CMakeFiles/Utkikk9000.dir/main.cpp.o
/home/bachelor/CLionProjects/Utkikk9000/main.cpp: In function ‘int main()’:
/home/bachelor/CLionProjects/Utkikk9000/main.cpp:17:51: error: ‘objects_names_from_file’ was not declared in this scope
     auto obj_names = objects_names_from_file(names);
                                                   ^
/home/bachelor/CLionProjects/Utkikk9000/main.cpp:27:48: error: ‘draw_boxes’ was not declared in this scope
         draw_boxes(frame, result_vec, obj_names);
                                                ^
/home/bachelor/CLionProjects/Utkikk9000/main.cpp:28:50: error: ‘show_console_result’ was not declared in this scope
         show_console_result(result_vec, obj_names);
                                                  ^
CMakeFiles/Utkikk9000.dir/build.make:62: recipe for target 'CMakeFiles/Utkikk9000.dir/main.cpp.o' failed
make[3]: *** [CMakeFiles/Utkikk9000.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/Utkikk9000.dir/all' failed
make[2]: *** [CMakeFiles/Utkikk9000.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/Utkikk9000.dir/rule' failed
make[1]: *** [CMakeFiles/Utkikk9000.dir/rule] Error 2
Makefile:118: recipe for target 'Utkikk9000' failed
make: *** [Utkikk9000] Error 2
```
And do I not need All the stuff in <yolo_console_dll.cpp> and <yolo_v2_class.cpp>?

**Comment by erlendhade** [comment]
Got help from someone else, problem was in CMakeLists.txt

**Comment by erlendhade** [comment]
```
cmake_minimum_required(VERSION 3.7)

project("Project name")

find_package(CUDA REQUIRED)
find_package(OpenCV REQUIRED COMPONENTS core highgui imgcodecs videoio)

add_library(darknet SHARED IMPORTED)

set(darknet_root "path_to_darknet_dir")

set_target_properties(darknet PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${darknet_root}/src;${CUDA_INCLUDE_DIRS}"
        IMPORTED_LOCATION "${darknet_root}/darknet.so"
        )

add_executable("Project name"
        main.cpp
        more_files)

set_target_properties("Project name" PROPERTIES
        CXX_STANDARD_REQUIRED ON
        CXX_STANDARD 14
        )

target_compile_definitions("Project name"
        PRIVATE GPU
        )

target_link_libraries("Project name"
        PRIVATE darknet
        PRIVATE ${CUDA_LIBRARIES}
        PRIVATE ${OpenCV_LIBRARIES}
        )
```
